const ENTER_KEY = 13
const ESCAPE = 27
const SPACE = 32
const BACKSPACE = 8
const DELETE = 46
const ARROW_UP = 38
const ARROW_DOWN = 40
const ARROW_LEFT = 37
const ARROW_RIGHT = 39
const NUM_LETTER_START = 48
const NUM_LETTER_END = 111
const SEMI_COLON = 186
const EQUAL_SIGN = 187
const COMMA = 188
const DASH = 189
const PERIOD = 190
const FORWARD_SLASH = 191
const OPEN_BRACKET = 219
const BACK_SLASH = 220
const CLOSE_BRAKET = 221
const SINGLE_QUOTE = 222

export {
  ENTER_KEY,
  ESCAPE,
  SPACE,
  BACKSPACE,
  DELETE,
  ARROW_UP,
  ARROW_DOWN,
  ARROW_LEFT,
  ARROW_RIGHT,
  NUM_LETTER_START,
  NUM_LETTER_END,
  SEMI_COLON,
  EQUAL_SIGN,
  COMMA,
  DASH,
  PERIOD,
  FORWARD_SLASH,
  OPEN_BRACKET,
  BACK_SLASH,
  CLOSE_BRAKET,
  SINGLE_QUOTE,
}
